import * as THREE from 'three';
import { RoundedBoxGeometry } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/geometries/RoundedBoxGeometry.js';
import { UltraHDRLoader } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/loaders/UltraHDRLoader.js';
import { RoomEnvironment } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/environments/RoomEnvironment.js';

const $=s=>document.querySelector(s),canvas=$('#stage'),loader=$('#loader'),title=$('#title'),detail=$('#detail'),pageEl=$('#page');
const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
const presets=[
 {title:'Cast<br>Optical Glass',detail:'Refractive shell, chromatic dispersion, polished inner volume.',accent:0x9be7ff,bg:0x17242b,mode:'glass'},
 {title:'Dichroic<br>Film',detail:'Thin-film interference changes color with every viewing angle.',accent:0xff70d7,bg:0x241737,mode:'dichroic'},
 {title:'Black<br>Titanium',detail:'Anisotropic machining lines under a dense smoked clearcoat.',accent:0x7e91ff,bg:0x111319,mode:'titanium'},
 {title:'Liquid<br>Mercury',detail:'A displaced metal skin that breathes under cursor pressure.',accent:0xc5f5ff,bg:0x172025,mode:'mercury'},
 {title:'Opal<br>Ceramic',detail:'Glazed mineral body with pearlescent grazing highlights.',accent:0xffa4bf,bg:0x35252d,mode:'opal'},
 {title:'Jade<br>Volume',detail:'Absorbing translucent depth, cool edge light, carved surface.',accent:0x64d2a4,bg:0x102c24,mode:'jade'},
 {title:'Frosted<br>Acrylic',detail:'Soft transmission, dense micro-roughness, luminous core.',accent:0xffd06a,bg:0x372716,mode:'frost'},
 {title:'Brushed<br>Copper',detail:'Directional metal grain with controlled oxidation color.',accent:0xff743d,bg:0x32150d,mode:'copper'},
 {title:'Smoked<br>Crystal',detail:'Dark refractive mass with bright caustic edges and inner form.',accent:0x9a8bff,bg:0x171326,mode:'smoke'},
 {title:'Spectral<br>Chrome',detail:'Mirror metal wrapped in a high-energy holographic coating.',accent:0x65f0d1,bg:0x111a25,mode:'spectral'}
];

const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight,false);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.02;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.transmissionResolutionScale=.85;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(31,innerWidth/innerHeight,.1,80);camera.position.set(0,.1,8.7);
const pmrem=new THREE.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(new RoomEnvironment(),.025).texture;scene.background=new THREE.Color(0x111318);
new UltraHDRLoader().load('./assets/royal_esplanade_2k.hdr.jpg',texture=>{texture.mapping=THREE.EquirectangularReflectionMapping;scene.environment=texture;scene.background=texture;scene.backgroundBlurriness=.22;scene.backgroundIntensity=.48;scene.environmentIntensity=1.15;pmrem.dispose();loader.classList.add('done')},undefined,()=>loader.classList.add('done'));

const hemi=new THREE.HemisphereLight(0xd9ecff,0x08080b,1.1);scene.add(hemi);const key=new THREE.DirectionalLight(0xffffff,3.8);key.position.set(-4,6,5);key.castShadow=true;key.shadow.mapSize.set(1536,1536);key.shadow.camera.near=.1;key.shadow.camera.far=20;scene.add(key);const cursorLight=new THREE.PointLight(0xffffff,45,12,1.7);scene.add(cursorLight);
const floor=new THREE.Mesh(new THREE.CircleGeometry(8,96),new THREE.MeshPhysicalMaterial({color:0x16171b,metalness:.35,roughness:.18,transparent:true,opacity:.9}));floor.rotation.x=-Math.PI/2;floor.position.y=-2.05;floor.receiveShadow=true;scene.add(floor);

const SIZE=1024,canvases=[],ctxs=[],maps=[],paintData=Array.from({length:10},()=>Array.from({length:6},()=>[]));
for(let i=0;i<6;i++){const c=document.createElement('canvas');c.width=c.height=SIZE;const x=c.getContext('2d',{alpha:false});canvases.push(c);ctxs.push(x);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=Math.min(16,renderer.capabilities.getMaxAnisotropy());maps.push(t)}
function noiseTexture(){const c=document.createElement('canvas');c.width=c.height=512;const x=c.getContext('2d'),im=x.createImageData(512,512);for(let i=0;i<im.data.length;i+=4){const n=112+Math.random()*34;im.data[i]=im.data[i+1]=im.data[i+2]=n;im.data[i+3]=255}x.putImageData(im,0,0);const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(4,4);return t}const micro=noiseTexture();
function base(face,preset){const x=ctxs[face],p=presets[preset],a=new THREE.Color(p.accent),b=new THREE.Color(p.bg);const c1=`#${b.clone().lerp(a,.12).getHexString()}`,c2=`#${a.clone().lerp(new THREE.Color(0xffffff),.18).getHexString()}`;const g=x.createLinearGradient(0,0,SIZE,SIZE);g.addColorStop(0,c1);g.addColorStop(.58,`#${b.getHexString()}`);g.addColorStop(1,c2);x.fillStyle=g;x.fillRect(0,0,SIZE,SIZE);x.save();x.translate(SIZE/2,SIZE/2);x.strokeStyle='rgba(255,255,255,.18)';x.lineWidth=2;
 if(face===0)for(let i=-8;i<=8;i++){x.beginPath();x.moveTo(-SIZE,i*54);x.bezierCurveTo(-220,i*54-80,220,i*54+80,SIZE,i*54);x.stroke()}
 if(face===1)for(let r=80;r<680;r+=54){x.beginPath();x.arc(0,0,r,0,Math.PI*2);x.stroke()}
 if(face===2)for(let i=0;i<14;i++){x.rotate(Math.PI/7);x.beginPath();x.moveTo(0,38);x.lineTo(0,460);x.stroke()}
 if(face===3)for(let y=-420;y<440;y+=80)for(let z=-420;z<440;z+=80){x.beginPath();x.arc(z+(y/80%2)*40,y,4,0,Math.PI*2);x.fillStyle='rgba(255,255,255,.24)';x.fill()}
 if(face===4){x.globalAlpha=.22;x.fillStyle='#000';x.fillRect(-350,-280,700,560);x.globalAlpha=.8;x.strokeStyle='rgba(255,255,255,.5)';x.lineWidth=12;x.beginPath();x.moveTo(-205,-125);x.quadraticCurveTo(-115,-178,-30,-120);x.moveTo(30,-120);x.quadraticCurveTo(115,-178,205,-125);x.stroke();x.lineWidth=8;x.beginPath();x.moveTo(-60,145);x.quadraticCurveTo(0,178,60,145);x.stroke()}
 if(face===5)for(let i=0;i<9;i++){x.rotate(.35);x.strokeRect(-70-i*25,-70-i*25,140+i*50,140+i*50)}x.restore();
 const grad=x.createLinearGradient(0,0,SIZE,0);grad.addColorStop(0,'rgba(255,255,255,.03)');grad.addColorStop(.5,'rgba(255,255,255,.22)');grad.addColorStop(1,'rgba(0,0,0,.08)');x.fillStyle=grad;for(let i=0;i<180;i++)x.fillRect(0,Math.random()*SIZE,SIZE,Math.random()<.8?1:2)
}
function dab(x,p){x.save();x.globalCompositeOperation='screen';x.fillStyle=p.color;x.shadowColor=p.color;x.shadowBlur=18;x.globalAlpha=.72;x.beginPath();x.arc(p.u*SIZE,(1-p.v)*SIZE,p.r,0,Math.PI*2);x.fill();x.restore()}
function redraw(preset){for(let f=0;f<6;f++){base(f,preset);paintData[preset][f].forEach(p=>dab(ctxs[f],p));maps[f].needsUpdate=true}}

const geometry=new RoundedBoxGeometry(3.35,3.35,3.35,10,.28),shaderRefs=[];
function material(map,index){const m=new THREE.MeshPhysicalMaterial({map,bumpMap:micro,bumpScale:.018,roughness:.12,metalness:.2,clearcoat:1,clearcoatRoughness:.04,envMapIntensity:1.8});m.onBeforeCompile=s=>{s.uniforms.uTime={value:0};s.uniforms.uDisplace={value:0};s.vertexShader=s.vertexShader.replace('#include <common>','#include <common>\nuniform float uTime; uniform float uDisplace;').replace('#include <begin_vertex>','#include <begin_vertex>\nfloat pulse=sin(position.x*4.2+uTime)+sin(position.y*5.1-uTime*.8)+sin(position.z*3.7+uTime*.65); transformed += normal*pulse*uDisplace;');m.userData.shader=s;shaderRefs[index]=s};m.customProgramCacheKey=()=>`material-lab-${index}`;return m}
const materials=maps.map(material),cube=new THREE.Mesh(geometry,materials);cube.rotation.set(.18,-.46,.02);cube.castShadow=true;cube.receiveShadow=true;scene.add(cube);
const innerMat=new THREE.MeshPhysicalMaterial({color:0x10151b,metalness:.55,roughness:.08,iridescence:1,iridescenceIOR:1.35,iridescenceThicknessRange:[120,680],envMapIntensity:2.5});const inner=new THREE.Mesh(new RoundedBoxGeometry(2.18,2.18,2.18,7,.22),innerMat);cube.add(inner);
const eyeMat=new THREE.MeshPhysicalMaterial({color:0x05070a,metalness:.82,roughness:.04,clearcoat:1,envMapIntensity:3});const face=new THREE.Group(),eyeGeo=new RoundedBoxGeometry(.22,.52,.12,5,.08);const eyeL=new THREE.Mesh(eyeGeo,eyeMat),eyeR=eyeL.clone();eyeL.position.set(-.48,.25,1.69);eyeR.position.set(.48,.25,1.69);const mouth=new THREE.Mesh(new RoundedBoxGeometry(.34,.07,.1,4,.035),eyeMat);mouth.position.set(0,-.48,1.69);face.add(eyeL,eyeR,mouth);cube.add(face);
const edge=new THREE.LineSegments(new THREE.EdgesGeometry(geometry,32),new THREE.LineBasicMaterial({color:0xffffff,transparent:true,opacity:.08}));cube.add(edge);

let current=Math.max(0,Math.min(9,parseInt(location.hash.slice(1),10)-1||0)),paint='#ff5d3a',phase='idle',phaseT=0,direction=1,blink=0;
function resetMaterial(m){Object.assign(m,{color:new THREE.Color(0xffffff),metalness:.1,roughness:.14,transmission:0,thickness:0,ior:1.5,dispersion:0,clearcoat:1,clearcoatRoughness:.04,iridescence:0,anisotropy:0,sheen:0,opacity:1,transparent:false,attenuationDistance:Infinity});m.attenuationColor.set(0xffffff);m.bumpScale=.018}
function applyPreset(){const p=presets[current];materials.forEach((m,i)=>{resetMaterial(m);m.roughness+=i*.018;switch(p.mode){case'glass':Object.assign(m,{transmission:.92,thickness:1.5,ior:1.42,dispersion:.07,roughness:.035,metalness:0});break;case'dichroic':Object.assign(m,{transmission:.42,thickness:.9,ior:1.62,roughness:.055,iridescence:1,iridescenceIOR:1.42,iridescenceThicknessRange:[90,920]});break;case'titanium':Object.assign(m,{metalness:1,roughness:.19,anisotropy:.92,anisotropyRotation:i*.55,clearcoat:.65});m.color.set(0x1b1d24);break;case'mercury':Object.assign(m,{metalness:1,roughness:.025,clearcoat:.25});break;case'opal':Object.assign(m,{metalness:0,roughness:.16,iridescence:.72,iridescenceIOR:1.3,iridescenceThicknessRange:[180,760],clearcoat:1});break;case'jade':Object.assign(m,{transmission:.38,thickness:2.2,ior:1.52,roughness:.16});m.color.set(0x7abf9d);m.attenuationColor.set(0x0f6e52);m.attenuationDistance=1.2;break;case'frost':Object.assign(m,{transmission:.76,thickness:1.1,ior:1.46,roughness:.27,dispersion:.015});m.bumpScale=.04;break;case'copper':Object.assign(m,{metalness:1,roughness:.24,anisotropy:1,anisotropyRotation:Math.PI*.5,clearcoat:.34});m.color.set(0xb65732);break;case'smoke':Object.assign(m,{transmission:.84,thickness:2.5,ior:1.58,roughness:.075,dispersion:.035});m.color.set(0x2d2a3c);m.attenuationColor.set(0x463778);m.attenuationDistance=.8;break;case'spectral':Object.assign(m,{metalness:1,roughness:.055,iridescence:1,iridescenceIOR:1.5,iridescenceThicknessRange:[120,1000],clearcoat:1});break}m.needsUpdate=true});
 inner.visible=['glass','dichroic','jade','frost','smoke'].includes(p.mode);innerMat.color.set(p.bg);innerMat.iridescence=p.mode==='dichroic'||p.mode==='spectral'?1:.25;eyeMat.color.set(p.mode==='titanium'?0xa8b5d5:0x05070a);floor.material.color.set(p.bg);cursorLight.color.set(p.accent);document.documentElement.style.setProperty('--accent','#'+new THREE.Color(p.accent).getHexString());title.innerHTML=p.title;detail.textContent=p.detail;pageEl.textContent=String(current+1).padStart(2,'0')+' / 10';location.hash=String(current+1).padStart(2,'0');redraw(current);
}
function go(d){if(phase!=='idle')return;direction=d;phase='out';phaseT=0}$('#prev').onclick=()=>go(-1);$('#next').onclick=()=>go(1);addEventListener('keydown',e=>{if(e.key==='ArrowLeft')go(-1);if(e.key==='ArrowRight')go(1)});let wheelWait=false;addEventListener('wheel',e=>{if(wheelWait||Math.abs(e.deltaY)<20)return;wheelWait=true;go(e.deltaY>0?1:-1);setTimeout(()=>wheelWait=false,700)},{passive:true});document.querySelectorAll('.swatch').forEach(b=>b.onclick=()=>{document.querySelectorAll('.swatch').forEach(x=>x.classList.remove('active'));b.classList.add('active');paint=b.dataset.color});$('.clear').onclick=()=>{paintData[current]=Array.from({length:6},()=>[]);redraw(current)};

const ray=new THREE.Raycaster(),pointer=new THREE.Vector2(3,3),smooth=new THREE.Vector2(),lastUV=new THREE.Vector2();let drawing=false,lastFace=-1,distance=0;
function setPointer(e){pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1)}function draw(){ray.setFromCamera(pointer,camera);const hit=ray.intersectObject(cube,false)[0];if(!hit)return;const f=hit.face.materialIndex||0,u=hit.uv;if(lastFace!==f)lastUV.copy(u);const dist=lastUV.distanceTo(u),steps=Math.max(1,Math.ceil(dist*SIZE/10));for(let i=1;i<=steps;i++){const q=lastUV.clone().lerp(u,i/steps),p={u:q.x,v:q.y,r:22,color:paint};paintData[current][f].push(p);dab(ctxs[f],p)}maps[f].needsUpdate=true;lastUV.copy(u);lastFace=f;distance+=dist}
canvas.addEventListener('pointerdown',e=>{setPointer(e);drawing=true;distance=0;lastFace=-1;canvas.setPointerCapture(e.pointerId);draw()});canvas.addEventListener('pointermove',e=>{setPointer(e);if(drawing)draw()});canvas.addEventListener('pointerup',e=>{drawing=false;canvas.releasePointerCapture(e.pointerId);if(distance<.012)blink=1});canvas.addEventListener('pointerleave',()=>{drawing=false;pointer.set(3,3)});
function resize(){camera.aspect=innerWidth/innerHeight;camera.fov=innerWidth<700?40:31;camera.position.z=innerWidth<700?9.7:8.7;camera.updateProjectionMatrix();renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<700?1.2:1.5));renderer.setSize(innerWidth,innerHeight,false)}addEventListener('resize',resize);
let prior=performance.now(),running=!document.hidden;document.addEventListener('visibilitychange',()=>running=!document.hidden);function frame(now){requestAnimationFrame(frame);if(!running||now-prior<1000/60)return;const dt=Math.min(.033,(now-prior)/1000),t=now*.001;prior=now;smooth.lerp(pointer,.065);cursorLight.position.set(smooth.x*4.4,smooth.y*3.1,4.2);if(!drawing&&!reduce){cube.rotation.y+=dt*.09;cube.rotation.x+=(smooth.y*.055+.16-cube.rotation.x)*.035;cube.rotation.z+=(-smooth.x*.035-cube.rotation.z)*.035}shaderRefs.forEach(s=>{if(s){s.uniforms.uTime.value=t;s.uniforms.uDisplace.value=presets[current].mode==='mercury'?.045:0}});blink=Math.max(0,blink-dt*2.1);const eyeScale=blink>.5?THREE.MathUtils.lerp(1,.06,Math.sin((blink-.5)*Math.PI)):1;eyeL.scale.y=eyeR.scale.y=eyeScale;inner.rotation.x=t*.08;inner.rotation.y=-t*.11;
 if(phase==='out'){phaseT+=dt*2.7;const q=Math.max(.001,1-phaseT);cube.scale.setScalar(q);cube.rotation.y+=dt*direction*3.2;if(phaseT>=1){current=(current+direction+10)%10;applyPreset();phase='in';phaseT=1}}else if(phase==='in'){phaseT-=dt*2.7;const q=1-Math.pow(Math.max(0,phaseT),3);cube.scale.setScalar(q);if(phaseT<=0){cube.scale.setScalar(1);phase='idle'}}renderer.render(scene,camera)}
applyPreset();resize();requestAnimationFrame(frame);setTimeout(()=>loader.classList.add('done'),2500);
