import test from "node:test";
import assert from "node:assert/strict";
import { compilePlaywright, defaultSpec, validateSpec } from "../core/compiler.js";

test("compiler emits role locators and a containment assertion", () => {
  const output = compilePlaywright(defaultSpec("http://localhost/checkout"));
  assert.match(output, /getByRole\("dialog", \{ name: "Choose delivery method" \}\)/);
  assert.match(output, /node\.contains\(document\.activeElement\)/);
  assert.doesNotMatch(output, /Gemini|generated by AI/i);
});

test("compiler blocks ambiguous targets", () => {
  const spec = defaultSpec("http://localhost/checkout");
  spec.assertion.ambiguous = true;
  assert.deepEqual(validateSpec(spec), ["Choose one exact target before export."]);
  assert.throws(() => compilePlaywright(spec), /Choose one exact target/);
});
